name: encling
channels:
  - huggingface
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - transformers=4.28.1
  - pytorch=2.0.1
  - ipywidgets=8.0.7
  - jupyterlab=4.0.3
  - pandas=1.5.3
  - matplotlib=3.7.1
  - seaborn=0.12.2
  - git=2.40.1
  - accelerate=0.21.0
  - gensim=4.3.1
  - scipy=1.11.1
  - scikit-learn=1.2.2
  - pip=23.2.1
  - pip:
      - annexremote==1.6.0
      - boto==2.49.0
      - brainspace==0.1.10
      - chardet==5.1.0
      - cython==0.29.36
      - datalad==0.19.2
      - distro==1.8.0
      - fasteners==0.18
      - future==0.18.3
      - h5py==3.9.0
      - himalaya==0.4.2
      - html5lib==1.1
      - humanize==4.7.0
      - imageio==2.31.1
      - iso8601==2.0.0
      - jaraco-classes==3.3.0
      - keyring==24.2.0
      - keyrings-alt==5.0.0
      - looseversion==1.3.0
      - lxml==4.9.3
      - mat73==0.60
      - mne==1.4.2
      - more-itertools==10.0.0
      - msgpack==1.0.5
      - neuromaps==0.0.4
      - nibabel==5.1.0
      - nilearn==0.10.1
      - nltk==3.8.1
      - patool==1.12
      - pooch==1.7.0
      - pycortex==1.2.7
      - pydot==1.4.2
      - pymoten==0.0.3
      - python-gitlab==3.15.0
      - requests-toolbelt==1.0.0
      - scipy==1.11.1
      - shapely==2.0.1
      - surfplot==0.2.0
      - threadpoolctl==3.2.0
      - voxelwise-tutorials==0.1.6
      - vtk==9.2.6
      - wget==3.2
prefix: /Users/snastase/opt/miniconda3/envs/encling
